### ISSUE TITLE
debian 11 and ubuntu 20.04 lts builds with -DSPGLIB_WITH_Fortran=ON fail

### ISSUE THREAD

**Issue by dmt4** [spglib/spglib#419] opened 2024-02-02 00:50 UTC
Hi, cmake fails in the configure step on both these. The cmake versions are 3.18 and 3.16 respectively. The error is:

CMake Error at cmake/compat/cmake_path.cmake:4 (if):
  if given arguments:

    "NOT" "IS_ABSOLUTE" "STREQUAL" "APPEND"

  Unknown arguments specified
Call Stack (most recent call first):
  fortran/CMakeLists.txt:31 (cmake_path)

It seems to finish trouble free with -DSPGLIB_WITH_Fortran=OFF.

Tried spglib v2.1.0 and v2.2.0, same result. All builds well on debian 12, the cmake version there is 3.25 if it helps.

**Comment by LecrisUT** [comment] 2024-02-02 04:49
It will take some effort to backport cmake functions.

Is it requested by other packages to update on those OS? Ubuntu 24.04 is just around the corner, and I'm not sure how often Debian cycles are.

**Comment by dmt4** [comment] 2024-02-02 06:51
Indeed, despite its usefulness cmake can be a pain at times.  I opened this issue in case it is a simple fix.

Debian cycles are apparently ~2y so is not that unreasonable to expect people to update if they want new things to work trouble free.

Feel free to close as wontfix/notplanned/whatever and sorry for the spam.

**Comment by LecrisUT** [comment] 2024-02-05 15:59
I will wait for the Fedora 40 release to see if there is some announcements about RHEL10 and if it makes sense to support RHEL9. If it makes sense to support RHEL9, that one uses an even older CMake version and it would fix this issue.

**Comment by dmt4** [comment] 2024-02-05 20:22
Almalinux 9.3 and similar have cmake v3.20 from "appstream" and probably so has rhel9.
Oddly enough al 8.9 has newer cmake v3.26.
None of these versions is affected by this issue.

**Comment by LecrisUT** [comment] 2024-02-05 20:34
~~Oh, at some point centos stream 9 updated to cmake 3.26. I've been waiting for a long time to go past 3.24. Which ones are still left with version < 3.24? Almalinux and any other?~~ (False alarm, it's still 3.20 for now :cry:)

**Comment by dmt4** [comment] 2024-02-05 21:37
opensuse 15.4 has 3.20, ubuntu 22.04 lts got 3.22. Again none of these affected.

**Comment by dmt4** [comment] 2024-02-05 21:47
I'm not sure where the complication is actually coming from. This is how I see things breaking down and all of them seem like they should have been supported in cmake for ages:

1. The .F90 file distributed as header.. no diff to a .h so no reason to not work
2. The .F90 file treated as source for .mod and _f08.so (not sure but think this in principle worked even 10y ago)
    (a) .mod is now to be copied along .h and the original .F90 so again no reason not to work.
    (b) _f90.so like any other .so should have been handled well from the first version of cmake.

**Comment by LecrisUT** [comment] 2024-02-05 22:05
The issue is mostly about packaging guidelines [^1] and the install location of the `.mod` files. Basically shared libraries are preferred, and since fortran doesn't have proper headers, using the .f90 files means that each consuming project would re-compile the contents that is effectively in the .so file. (Note that the .f90 files are not just c-interface links). And since the .mod files should be installed in a compiler specific folder, we need to implement something similar to `CMAKE_INSTALL_INCLUDEDIR`, where I'm using that cmake_path compatibility.

Edit: more clarification, basically we have to ensure that other projects being packaged are also consumed by linking to the .so file instead of re-compiling from the .f90 files

[^1]: https://docs.fedoraproject.org/en-US/packaging-guidelines/Fortran/

**Comment by dmt4** [comment] 2024-02-05 23:21
Ok, it is the compiler specific path that is the issue indeed. I see I have `/usr/include/Spglib/GNU-13.2.1/spglib_f08.mod` from the system package.

There is extra trouble though, the fortran compiled .o files and libs resulting from them are not necessarily compiler independent either (for a few reasons) and I don't see this addressed in the linked guidelines at all.  If the f lib is going to be allowed in the general place it is in currently then seems a little overzealous to create compiler specific module and all that.. In the end only one compiler (the system one) will ever read that module file (and most likely it is that compiler that will pass the compiler-specific f lib to the linked) and a it will be kept in sync with that compiler's version too.

In the HPC-like use mode, again only a specific compiler version is used for all and a whole directory tree is dedicated to it so it is a useless complication to create out additional oddly named paths inside of this.

**Comment by LecrisUT** [comment] 2024-02-05 23:58
> There is extra trouble though, the fortran compiled .o files and libs resulting from them are not necessarily compiler independent either

Indeed, but there's no discussion on where to put those yet. Iirc ther could be a `/usr/lib64/gfortran` that can house those. In principle you can still install multiple arthitectures in `/usr/local` if you manually re-define the library path for the secondary one (after you change he `Config.cmake` to search for appropriate compiler path).

Another nuance is `find_library`, `find_path` for non-cmake projects. CMake search path does not consider compiler-name in the search, so we cannot dictate a custom path for the libraries by ourselves.

Right now gfortran is the only packaged fortran compiler until flang-new becomes usable, so there is no precedence of how to package abi-incompatible libraries. My hope is that with CXX modules, it will have similar design issues and the guidelines will be addressed quicker over there.

> oddly named paths inside

I agree with you on this. The only reason I chose that format was because of fortran stdlib [^1], and in lieu of any coordination efforts, that's the closest we have to a reference. The naming convention should have been backwards and without the comipler version.

[^1]: https://github.com/fortran-lang/stdlib/blob/8c7461dee1f10ea7042c6819aa11d96d9ebbc519/config/CMakeLists.txt#L3

**Comment by alinelena** [comment] 2024-02-06 10:30
@dmt4 @LecrisUT this is something I raised for few years in a row at esl and since both of you will be there maybe is a good idea to have again a chat about it there.

on the CMake design, one bit is to use KISS principles... do not be tempted to solve problems that one may not have just because in future they may. 

@LecrisUT unfortunately Fortran community jumped from pure denial of CMake to 120% embracing it... transferring complex patterns from C++ and other more sophisticated software fields in scientific computing.

**Comment by LecrisUT** [comment] 2024-02-06 10:43
> since both of you will be there maybe is a good idea to have again a chat about it there.

Totally agree, looking forward to that.

> on the CMake design, one bit is to use KISS principles... do not be tempted to solve problems that one may not have just because in future they may.

On the consumer project side, I agree. But for this one, I have plans to package it in [CmakeExtraUtils](https://github.com/LecrisUT/CmakeExtraUtils) so that we don't re-invent the wheel and we have a more concentrated effort on these nuances. DynamicVersion is already available there and fully tested. Feel free to use it.

**Comment by LecrisUT** [comment] 2024-08-13 12:07
Going back through old issues. There has been quite some refactoring, particularly with (properly) bumping minimum CMake version to 3.25 since now Debian 12 + and Ubuntu 24.04 are out. How much is this issue still relevant?

**Comment by dmt4** [comment] 2024-08-13 17:45
Not much I guess. Whoever wants to run on old systems probably has access to new enough cmake.

**Comment by LecrisUT** [comment] 2024-08-14 08:14
`pip install cmake` ftw :D

**Closed as completed by LecrisUT** 2024-08-14 08:14 UTC
