### ISSUE TITLE
Problem with Wyckoff letters

### ISSUE THREAD

**Issue by lauri-codes** [spglib/spglib#100] opened 2020-05-05 13:12 UTC
Hi @atztogo!

First thanks for the new version with crystallographic orbits, it has been very useful.

I'm encountering another issue that does not seem to be related to the detection of orbits, but to the detection of Wyckoff letters. Running the following code:

```python
import spglib

positions = [
    [0.90851861, 0.21051529000000002, 0.25727981],
    [0.46576772999999994, 0.66183489, 0.26060525],
    [0.09148138999999995, 0.7894847099999999, 0.7572798100000001],
    [0.53423227, 0.33816511, 0.76060525],
    [0.27579234999999996, 0.08858242999999999, 0.2558383],
    [0.7242076499999999, 0.91141757, 0.7558383],
    [0.7854356299999999, 0.74489282, 0.023756],
    [0.5475107199999999, 0.19097495000000003, 0.25401026],
    [0.14379994999999998, 0.71511876, 0.2589846499999999],
    [0.78800764, 0.74431709, 0.49152573],
    [0.21456436999999998, 0.25510717999999993, 0.523756],
    [0.45248927999999994, 0.80902505, 0.7540102599999999],
    [0.8562000499999998, 0.28488124, 0.75898465],
    [0.21199235999999994, 0.25568291, 0.99152573],
]
numbers = [55, 55, 55, 55, 80, 80, 53, 53, 53, 53, 53, 53, 53, 53]
lattice = [
    [11.32741769, -0.10246116, 0.0],
    [-2.84874166,7.50332458, 0.0],
    [0.0, 0.0, 8.49408944]
]
cell = (lattice, positions, numbers)

# Get symmetry dataset
symmetry_dataset = spglib.get_symmetry_dataset(cell, symprec=0.1)

# Print site information for each atom
spg = symmetry_dataset["number"]
wyckoff_letters = symmetry_dataset["wyckoffs"]
equivalent_atoms = symmetry_dataset["equivalent_atoms"]
orbits = symmetry_dataset["crystallographic_orbits"]
site_symmetry_symbols = symmetry_dataset["site_symmetry_symbols"]
print("Belongs to space group: {}".format(spg))
for w, o, e, s in zip(wyckoff_letters, orbits, equivalent_atoms, site_symmetry_symbols):
    print(w, o, e, s)
```

I get the following output:
```
Belongs to space group: 11
f 0 0 1
f 1 1 1
f 0 0 1
f 1 1 1
e 4 4 m
e 4 4 m
f 6 6 1
e 7 7 m
f 8 8 1
f 9 9 1
f 6 6 1
e 7 7 m
f 8 8 1
f 9 9 1
```

You can notice that 10 atoms have been assigned the letter f, which should have a multiplicity of 4 in space group 11 [according to Bilbao](https://www.cryst.ehu.es/cgi-bin/cryst/programs/nph-normsets?from=wycksets&gnum=11). The orbits and equivalent atoms indicate that the atoms come in groups of two, never four.

Could you have a look at what could be the problem, or if I'm doing something silly.

**Comment by blokhin** [comment] 2020-05-05 13:29
This structure is described by [PAULING FILE](https://mpds.io/phase/Cs2HgI4/11/mP14). I attach a screen-shot of the symmetry analysis done using STRUCTURE TIDY.

![S1404748](https://user-images.githubusercontent.com/177388/81071451-07ef4e00-8ee5-11ea-9057-e0ac9f4bce5b.png)

**Comment by atztogo** [comment] 2020-05-05 23:42
Thanks for your report. I confirmed that spglib is not working as what I expect. So I have to fix it if possible. What should not be is, after standardization, the symmetry is lowered by the following script. Another clear issue is that number of rotations is found 4, but it should be 8. This number lowering can happen when the non-primitive cell is given and the point group of the lattice breaks the crystallographic point group. But your crystal is already primitive, so it should be 8, if the space group found is preferred. The algorithm has to be modified to check these consistences.

Handling large symmetry tolerance is very tough, which makes spglib code complicated as written in the manuscript (https://arxiv.org/abs/1808.01590). Otherwise implementation of symmetry finder is not as difficult. However once the issue is found, I can try to be able to handle more cases.

```python
import spglib


def print_symmetry_info(cell, symprec):
    symmetry_dataset = spglib.get_symmetry_dataset(cell, symprec=symprec)
    spgtype = symmetry_dataset["international"]
    spgnum = symmetry_dataset["number"]
    wyckoff_letters = symmetry_dataset["wyckoffs"]
    equivalent_atoms = symmetry_dataset["equivalent_atoms"]
    orbits = symmetry_dataset["crystallographic_orbits"]
    site_symmetry_symbols = symmetry_dataset["site_symmetry_symbols"]
    print("Belongs to space group: {}({})".format(spgtype, spgnum))
    for w, o, e, s in zip(wyckoff_letters, orbits, equivalent_atoms,
                          site_symmetry_symbols):
        print(w, o, e, s)

    print("Rotations")
    for r in symmetry_dataset["rotations"]:
        print(r)


def get_std_cell(cell, symprec):
    d = spglib.get_symmetry_dataset(cell, symprec=symprec)
    std_cell = (d['std_lattice'], d['std_positions'], d['std_types'])
    return std_cell


def main():
    positions = [
        [0.90851861, 0.21051529000000002, 0.25727981],
        [0.46576772999999994, 0.66183489, 0.26060525],
        [0.09148138999999995, 0.7894847099999999, 0.7572798100000001],
        [0.53423227, 0.33816511, 0.76060525],
        [0.27579234999999996, 0.08858242999999999, 0.2558383],
        [0.7242076499999999, 0.91141757, 0.7558383],
        [0.7854356299999999, 0.74489282, 0.023756],
        [0.5475107199999999, 0.19097495000000003, 0.25401026],
        [0.14379994999999998, 0.71511876, 0.2589846499999999],
        [0.78800764, 0.74431709, 0.49152573],
        [0.21456436999999998, 0.25510717999999993, 0.523756],
        [0.45248927999999994, 0.80902505, 0.7540102599999999],
        [0.8562000499999998, 0.28488124, 0.75898465],
        [0.21199235999999994, 0.25568291, 0.99152573],
    ]
    numbers = [55, 55, 55, 55, 80, 80, 53, 53, 53, 53, 53, 53, 53, 53]
    lattice = [
        [11.32741769, -0.10246116, 0.0],
        [-2.84874166, 7.50332458, 0.0],
        [0.0, 0.0, 8.49408944]
    ]
    cell = (lattice, positions, numbers)

    print("----------- original symprec=0.1 ------------")
    print_symmetry_info(cell, 0.1)

    print("----------- standardized symprec=1e-5 ------------")
    std_cell = get_std_cell(cell, 0.1)
    print_symmetry_info(std_cell, 1e-5)


main()
```

The output is
```
% python test.py                                      [~/lauri]
----------- original symprec=0.1 ------------
Belongs to space group: P2_1/m(11)
f 0 0 1
f 1 1 1
f 0 0 1
f 1 1 1
e 4 4 m
e 4 4 m
f 6 6 1
e 7 7 m
f 8 8 1
f 9 9 1
f 6 6 1
e 7 7 m
f 8 8 1
f 9 9 1
Rotations
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[-1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
[[-1  0  0]
 [ 0 -1  0]
 [ 0  0  1]]
[[ 1  0  0]
 [ 0  1  0]
 [ 0  0 -1]]
----------- standardized symprec=1e-5 ------------
Belongs to space group: P2_1(4)
a 0 0 1
a 1 1 1
a 0 0 1
a 1 1 1
a 4 4 1
a 4 4 1
a 6 6 1
a 7 7 1
a 8 8 1
a 9 9 1
a 6 6 1
a 7 7 1
a 8 8 1
a 9 9 1
Rotations
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[-1  0  0]
 [ 0  1  0]
 [ 0  0 -1]]
```

**Comment by atztogo** [comment] 2020-05-06 00:35
Note to me: Spglib gives correct results for symprec=0.2 (P2_1/m(11)) and symprec=0.05 (P2_1(4)).

**Comment by lauri-codes** [comment] 2020-05-06 05:04
Thank you for the prompt reply. I can imagine that as tolerances grow the symmetry detection becomes a very complicated task. Let me know if you figure out something or if I can help with anything.

**Comment by atztogo** [comment] 2020-05-06 10:08
I think this (specific) issue has been fixed by this commit, https://github.com/spglib/spglib/commit/44ccd8e363f0022cae7ca0f06441dd7c5141ddd2. This fix is included in the develop branch.

## what was done
This is memo for me. In this commit, one crsytallographic check was added: 

https://github.com/spglib/spglib/blob/44ccd8e363f0022cae7ca0f06441dd7c5141ddd2/src/site_symmetry.c#L413

`multiplicity` is obtained from the database in spglib (same as that in ITA). This number is given for the conventinal unit cell. `ref_multiplicity = num_equivalent_atoms * N`. `num_equivalent_atoms` is the number of symmetrically equivalent atoms in primitive cell found by spglib. This can be found wrongly, so crystallographicaly check is needed. `N` is the number of primitive translations in the conventional unit cell. `N` is known from the space group type. This is repeated adjusting tolerance in this loop:

https://github.com/spglib/spglib/blob/44ccd8e363f0022cae7ca0f06441dd7c5141ddd2/src/site_symmetry.c#L99-L124

This loop is one of the loops to make the symmetry finding consistent to the crystallographic information.

**Comment by atztogo** [comment] 2020-05-15 13:33
I think now it's OK. So I will close this issue. But in case not OK, please reopen this issue.

**Closed by atztogo** 2020-05-15 13:33 UTC
