### ISSUE TITLE
Return spin flip information for magnetic symmetry in python interface

### ISSUE THREAD

**Issue by jaemolihm** [spglib/spglib#150] opened 2022-03-26 17:14 UTC
Hi, thanks a lot for developing and maintaining this very nice package!

From the comments in the python code, it seems that magnetic symmetry with non-collinear magnetism is supported. But, `spglib.get_symmetry` does not give an information about whether the symmetry involves time reversal or not. For example, in the following code, first four symmetries do not have time reversal, and the others do.

1. Is this information available in other python interface function?
2. Even if this information is available in other interface function, it would be useful to have this information in the output of `spglib.get_symmetry`.

```python3
import spglib

lat = [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
pos = [[0., 0., 0.], [0., 0., 0.5]]
num = [0, 0]
magmom = [[0., 0., 1.], [0., 0., -1.]]
cell = (lat, pos, num, magmom)

print(spglib.get_symmetry(cell).keys())
print(spglib.get_symmetry(cell)["translations"])
```
Output:
```
dict_keys(['rotations', 'translations', 'equivalent_atoms', 'primitive_lattice'])
[[-0.  -0.  -0. ]
 [-0.  -0.  -0. ]
 [-0.  -0.  -0. ]
 [-0.  -0.  -0. ]
 [-0.  -0.   0.5]
 [-0.  -0.   0.5]
 [-0.  -0.   0.5]
 [-0.  -0.   0.5]]
```

**Comment by atztogo** [comment] 2022-03-27 09:37
@jaemolihm, could you tell me what "time reversal" means?

**Comment by jaemolihm** [comment] 2022-03-27 09:58
I mean spin flip.

**Comment by atztogo** [comment] 2022-03-27 10:46
Spin flip is restricted to the collinear case (`tensor_rank = 0`). I can implement for the non-colllinear case if you help me to test it. But what is the expected behaviour?

For example, currently following two options are implemented,

with an on-site vector `m=(m_x, m_y, m_z)` at the atomic point `r` and a space group operation `(R|t)`.

```
m' = R m
```
and
```
m' = det(R) R m
```

where `m'` is the on-site vector at `r' = (R|t) r`.

**Comment by jaemolihm** [comment] 2022-03-27 10:57
I see. Thank you for the explanation. So spin flip is not currently implemented for non-collinear case. Sorry for my confusion.

I was thinking about symmetries where `m' = -Rm` or `m' = -det(R) R m`.

**Comment by lan496** [comment] 2022-07-11 09:15
Now PR https://github.com/spglib/spglib/pull/162 , which will solve this issue, has merged to `develop`.
After the current `develop` branch is merged into `master`, I think this issue can be closed.

As the PR changes the behavior of `get_symmetry` with zero magmoms (corresponding to type-II MSG), I've prepared a workaround to reproduce the previous behavior as follows, which ignores `time_reversal` information and only take unique rotations and translations:
```python
import numpy as np
from spglib import get_symmetry

lattice = [[4, 0, 0], [0, 4, 0], [0, 0, 4]]
positions = [[0, 0, 0]]
numbers = [1]
magmoms = [0]  # Gray

nonspin_symmetry = get_symmetry((lattice, positions, numbers))
assert len(nonspin_symmetry['rotations']) == 48

symmetry = get_symmetry((lattice, positions, numbers, magmoms))
# Half of operation is time_reversal=True and the others is time_reversals=False
assert len(symmetry['rotations']) == 96

# To reproduce previous spglib's behavior, unique by rotation and translation
rotations = []
translations = []
for r, t in zip(symmetry['rotations'], symmetry['translations']):
    is_unique = True
    for ri, ti in zip(rotations, translations):
        if np.allclose(r, ri) and np.allclose(t, ti):
            is_unique = False
            break
    if is_unique:
        rotations.append(r)
        translations.append(t)
rotations = np.array(rotations)
translations = np.array(translations)

assert len(rotations) == 48
```

**Comment by jaemolihm** [comment] 2022-07-12 07:25
@lan496 Thanks for the work! The magnetic symmetry operation functionality will be very useful.

I have one question: does spglib now (or in the near future) calculate symmetry operations that involves time reversal? For example, does spglib detect “translation by 0.5 and time reversal” symmetry of an antiferromagnet (with vector magmoms is given as input)?

**Comment by lan496** [comment] 2022-07-12 08:29
@jaemolihm 
Yes, `get_symmetry` with spins (shape=(N, )) or magmoms (shape=(N, 3)) can calculate symmetry operation with time reversals at `develop` branch.
So you can use it by cloning spglib's repository and manually building it for now.

The description of returned time-versal information is [here](https://github.com/spglib/spglib/blob/develop/python/spglib/spglib.py#L111-L115).
Unit tests for [collinear spins](https://github.com/spglib/spglib/blob/71cc0527afe1d64ef81d11fae1908bc4d34fd4b8/python/test/test_collinear_spin.py) and [magmoms](https://github.com/spglib/spglib/blob/71cc0527afe1d64ef81d11fae1908bc4d34fd4b8/python/test/test_site_tensors.py) may be useful to figure out the usage.

These magnetic-space-group-related features will be released in the next (or near future) major version.
The input flags for `get_symmetry` may be changed from the current `develop` version and the major release, but I think the behavior to find magnetic symmetry operation will not change unless some critical bug is found.

Also, if you find any unexpected behavior, please open an issue with your magnetic structure!
I have checked the current implementation correctly finds the magnetic symmetry operations of [MAGNDATA](http://webbdcrista1.ehu.es/magndata/)'s structures, but unit test is still so scarce...

**Comment by jaemolihm** [comment] 2022-07-12 08:40
Thanks a lot for the explanation! I will try and report if I find any unexpected behavior.

**Comment by lan496** [comment] 2022-08-20 23:35
@atztogo @jaemolihm I think this issue can be closed now since `spglib.get_magnetic_symmetry` returns spin-flip information at spglib v.2.0.0.

**Comment by atztogo** [comment] 2022-08-21 00:26
Yes, @lan496. I will close this issue, but @jaemolihm please reopen this issue whenever you need.

**Closed by atztogo** 2022-08-21 00:26 UTC
