### ISSUE TITLE
Cannot map all reducible kpoints to irreducible ones

### ISSUE THREAD

**Issue by mfherbst** [spglib/spglib#101] opened 2020-05-12 07:10 UTC
In some cases the returned rotations and irreducible kpoints are not compatible in the sense that some reducible kpoints cannot be manually mapped to any of the provided irreducible kpoints under the returned rotations.

A simple reproducer:
```python
import numpy as np
import spglib

lattice = np.array([[1.0, 0.0, 0.0],
                    [0.0, 1.0, 0.0],
                    [0.0, 0.0, 1.0]])
positions = [[0., 0., 0.],
             [0., 0.5, 0.5]]
numbers = [1, ] * 2
cell = (lattice, positions, numbers)
mesh = [1, 2, 3]

mapping, grid = spglib.get_ir_reciprocal_mesh(mesh, cell, is_shift=[0, 0, 0],
                                              is_time_reversal=False)
syms = spglib.get_symmetry(cell)

def isinteger(a):
    return np.all(np.abs(a - np.array(a, dtype=int)) < 1e-5)

error = False
for kred in grid:
    # print("kred", kred.astype(float)/mesh)
    found = False
    for kirred in grid[np.unique(mapping)]:
        if found:
            break
        # print("  kirred", kirred / np.array(mesh, dtype=float))
        for r in syms['rotations']:
            test = kred / mesh - np.dot(np.transpose(r), kirred / mesh)
            # print("    test", test)
            if isinteger(test):
                print(kred, "is represented by", kirred)
                found = True
                break
    if not found:
        print(kred, "could not be reduced")
        error = True

if error:
    raise SystemExit("Some could not be reduced")
```

**Comment by atztogo** [comment] 2020-05-12 08:32
This can happen when the input cell is not standardized. What is the behaviour that you expect for crystals oriented unconventionally?

**Comment by mfherbst** [comment] 2020-05-12 09:27
Thanks four your quick reply.

I would expect that in any case the reducible k-points I get can be mapped to the irreducible k-points by the symmetry, irregardless of the cell. Otherwise, how can you check the returned symmetries are correct?

Maybe I should give you a little context. We currently use the ability to map between irreducible and reduced k-Points using the rotations determined by spglib to symmetrise certain quantities (density, forces, etc.) during computation. Therefore we explicitly check in a routine similar to my code example that such a mapping between k-points can be found using the results of spglib.

To me it seems natural to assume that such a mapping exists using the data returned from the library. But I am far from understanding all the details about k-Point symmetries, so maybe there are good reasons why this assumption is wrong. In that case I am more than happy to hear your thoughts!

**Comment by atztogo** [comment] 2020-05-12 10:46
Spglib works only for ideal cases. It is difficult to make grid symmetry works for any input of users. 

User's inputs of crystal structure and regular mesh sampling numbers (three integers) can be inconsistent. Some details are found in this paper, https://arxiv.org/abs/1902.03257. A possible solution written in this manuscript is the sampling is done by a distance measure and let software to suggest grid points so that symmetry can be used the best. In this paper, they allow the generalized regular grid, too. 

Another solution is to raise exception if something goes wrong or just fall into no symmetry.

**Comment by mfherbst** [comment] 2020-05-12 18:38
Thanks for the reply and the reference. I can imagine, to get symmetries to work for general user input is a real challenge. I just wanted to make sure the observed behaviour is as intended. Maybe it would be a good idea to flag an error in the cases of non-standardised cells on the spglib side, in case this is not already done?

Regarding our code, your advised solution would be to force users to standardise the cell in such a case before calling using the computational routines (and thus spglib)?

**Comment by atztogo** [comment] 2020-05-12 22:46
> I just wanted to make sure the observed behaviour is as intended.

This I don't know, or I don't determine yet. This question contains two parts, theoretical part and computer implementation part. This issue is more in the theoretical part. This is the typical difficulty in scientific code. Often we have to implement before clear definition. When the code is personal, it's ok. But increasing user base, serious.

> it would be a good idea to flag an error in the cases of non-standardised cells on the spglib side, in case this is not already done?

I agree. But probably we may need to consider extending spglib to support the generalized regular grid. The reason is written below.

> Regarding our code, your advised solution would be to force users to standardise the cell in such a case before calling using the computational routines (and thus spglib)?

The standardized cell is not a primitive cell when having centring. If this is not the matter, what you wrote can be a solution. If it has centring, for example, for the primitive cell of body-centred tetragonal, the regular grid can not be used to support symmetry well. For these cases, we have to think about using the generalized regular grid.

This generalized regular grid can have side-effect in many routines in the code. Some routine can depend on the rule of making regular grids (indexing etc). For example, my phonon code, the linear tetrahedron method has to be updated to accept generalized regular grid.

**Comment by mfherbst** [comment] 2020-05-15 07:10
Thanks for the detailed answer. I'll try to go with standard grids and using standardised cells for now where possible and issue a warning if the cell is more general.

I understand that the error I got in my original post is expected behaviour for the time being, so feel free to close this issue.

**Comment by antoine-levitt** [comment] 2020-05-15 07:30
I don't understand why the current behavior is considered OK. We use spglib for computational reduction with respect to a standard unsymmetrized monkhorst-pack grid. From that point of view it's forgivable that not all symmetries are found or that the IBZ is too big, but what's returned in the example @mfherbst showed is an inconsistency between the IBZ and the symmetries. Surely that's a bug? In that case I would expect spglib to make sure that all points in the RBZ can indeed be mapped to the IBZ, and if that is not the case to just add them to the IBZ.

**Comment by atztogo** [comment] 2020-05-15 08:27
The current behaviour is not OK. But I thought it was OK. If those that don't work are defined as corner cases, it's not a bug. Once we know the issue, and if we want to fix it (issue is clear and we have any means to fix it), it is considered as a bug.

We have a better solution such as written in the paper https://arxiv.org/abs/1902.03257. @antoine-levitt , your contribution is very welcome if you want to fix this issue. But before you start to work, I want to ask if you read and understand this paper and how much your knowledge on crystallography. These knowledge is quite important to _design_ functions for general users.

To design functions for general users is uneasy. Spglib was made for me to satisfy my use cases. After some time, other people started to use spglib. So I work as a volunteer to maintain and develop spglib to be better, which is non-trivial amount of work but with little benefit.

After some quick thought, the direction we might go to fix this issue is
1. For regular grid with three integers, the symmetrical inconsistency would be detected. For this, we have to consider about the algorithm to make it fast and memory friendly. Sometime the mesh can be ~10000^3.
2. Implementation of generalized regular grid (with distance but not with mesh numbers of three intergers). We can simply use https://github.com/msg-byu/autoGR. But in my experience, to support a scientific code for many years is uneasy. This is simply because you can get little benefit to support scientific software, but we are always busy and it's difficult to have enough time to work for. So if we rely on other scientific code, once the project stops, we will be lost. So if the feature is very useful and possibly implemented, I think it's a choice to implement it by ourselves, which makes the maintenance easy, too. To implement this, careful consideration on usability and user-friendlyness is necessary. For me, for example, to work with tetrahedron method is important.
3. The reciprocal space functions above should be separated from spglib. Spglib is already too popular, if they are included in main spglib, we have to support them very carefully. Change of API requires major version change, but for this kind of experimental implementation of a feature, we often realize the change of API is necessary to be more useful or better design after some real use. So it can be a good idea to offer it as another code.

**Comment by antoine-levitt** [comment] 2020-05-15 12:13
I perfectly understand that writing and maintaining such a piece of software is a hard and unrewarding job: I appreciate that it exists at all, it made our life with @mfherbst already much easier! OK, for the time being we'll just check by hand that the reducible kpoints can indeed be reduced.

**Comment by mfherbst** [comment] 2020-05-15 12:20
I can only agree! Thanks for maintaining this code, and sorry if we came a across as asking for too much.

**Comment by atztogo** [comment] 2020-06-17 07:02
I spent some time to write my note how to treat symmetry of grids. In my plan, it can not be a simple fix, but will be a new feature written from scratch including Smith normal form calculator (done https://github.com/atztogo/snf3x3), which means I have to carefully define API. New API is what I wanted to avoid, but no way around.

**Comment by mfherbst** [comment] 2020-06-17 07:33
Thanks for the update and for looking into this! There is no hurry on our end, so feel free to take your time to redesign as needed.

**Comment by atztogo** [comment] 2021-03-02 07:08
This is done in https://github.com/atztogo/kspclib, though no documentation yet. The kpoint grid feature may be separated from spglib in the next major release. I need to consider it carefully because spglib is widely used.

**Comment by antoine-levitt** [comment] 2021-03-02 07:58
OK, let us know when you consider it ready for prime time and we can make the switch. In particular I see you support the tetrahedron method, which is cool!

**Comment by mfherbst** [comment] 2021-03-02 08:08
Very nice! Thanks for the update. Looking forward to giving it a try.

**Comment by atztogo** [comment] 2021-03-02 08:26
Just a minor comment. For a rotation matrix in reciprocal space defined by

k' = Rk

where k is given in the reduced coordinates, i.e., with respect to reciprocal basis vectors, I think the broken symmetry of the grid of R is detected whether the following matrix (R') becomes an integer matrix or not,

R' = diag(mesh) R diag(mesh)^-1,

where mesh is the three integer values to generate a uniform grid (the conventional sampling mesh). So you may screen those rotation matrices that satisfy the above condition for the mesh. This doesn't mean the symmetry of the crystal itself is broken, but only for the grid. This problem can be avoided using a generalized regular grid to be provided in the future. :)

**Comment by atztogo** [comment] 2022-08-05 07:53
I will close this issue because no discussion for a while.

**Closed by atztogo** 2022-08-05 07:53 UTC
